import {
  Car,
  BedDouble,
  Wind,
  Waves,
  UtensilsCrossed,
  Baby,
  Toilet,
  Dumbbell,
} from "lucide-react";

import { Comment2, ListingItem, Property } from "./types";
import { Comment } from "./types";
/* ─── Image constants ─────────────────────────────────── */
export const BEDROOM_IMAGES = [
  "https://images.unsplash.com/photo-1633948393301-d43e3ec0e5cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1633944095397-878622ebc01c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
];

export const MAIN_IMAGE =
  "https://images.unsplash.com/photo-1562925246-25f01be5471c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080";

export const MOSQUE_IMAGE =
  "https://images.unsplash.com/photo-1632782532013-bd3f5f9197db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600";

export const THUMB_IMAGES = [
  "https://images.unsplash.com/photo-1761194412110-9998acafc0ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
  "https://images.unsplash.com/photo-1551361415-69c87624334f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
  "https://images.unsplash.com/photo-1613977257365-aaae5a9817ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
  "https://images.unsplash.com/photo-1724582586529-62622e50c0b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
];

export const CARD_IMAGES = [
  "https://images.unsplash.com/photo-1644057501622-dfa7dd26dbfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1710883734891-93709398496d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1601221998768-c0cdf463a393?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1774280954999-9758f11f3d41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1759472659432-3232e42d04d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1760067537116-de1f76fe8f95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1760067537740-faa11f7bdf1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1777880305920-e542f575f4e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  "https://images.unsplash.com/photo-1710224002849-a76ea1068b0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
];

export const properties: Property[] = [
  {
    id: 1,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 424,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.5,
    location: "تهران، الهیه",
    priceType: "monthly",
    image: CARD_IMAGES[0],
  },
  {
    id: 2,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 406,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    discountPrice: 5900000,
    rating: 4.8,
    location: "تهران، نیاوران",
    priceType: "nightly",
    image: CARD_IMAGES[1],
  },
  {
    id: 3,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 403,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.9,
    location: "تهران، فرمانیه",
    priceType: "monthly",
    image: CARD_IMAGES[2],
  },
  {
    id: 4,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 424,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.5,
    location: "تهران، زعفرانیه",
    priceType: "monthly",
    image: CARD_IMAGES[3],
  },
  {
    id: 5,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 406,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    discountPrice: 5900000,
    rating: 4.7,
    location: "تهران، قیطریه",
    priceType: "nightly",
    image: CARD_IMAGES[4],
  },
  {
    id: 6,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 403,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.9,
    location: "تهران، شهرک غرب",
    priceType: "monthly",
    image: CARD_IMAGES[5],
  },
  {
    id: 7,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 424,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.5,
    location: "تهران، دروس",
    priceType: "monthly",
    image: CARD_IMAGES[6],
  },
  {
    id: 8,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 406,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    discountPrice: 5900000,
    rating: 4.6,
    location: "تهران، جردن",
    priceType: "nightly",
    image: CARD_IMAGES[7],
  },
  {
    id: 9,
    title: "خانه ویلایی با پارکینگ اختصاصی",
    type: "ویلا",
    area: 403,
    beds: 3,
    baths: 2,
    parking: 1,
    price: 4500000,
    rating: 4.8,
    location: "تهران، ونک",
    priceType: "monthly",
    image: CARD_IMAGES[8],
  },
];

export const TOTAL_PAGES = 10;

/* ─── Amenities ───────────────────────────────────────── */
export const AMENITIES = [
  { icon: Wind, label: "کولرگازی" },
  { icon: Waves, label: "سونا" },
  { icon: Car, label: "پارکینگ" },
  { icon: Waves, label: "استخر" },
  { icon: UtensilsCrossed, label: "آشپزخانه" },
  { icon: Baby, label: "اتاق نوزاد" },
  { icon: Dumbbell, label: "سالن ورزشی" },
  { icon: Toilet, label: "سرویس بهداشتی" },
  { icon: BedDouble, label: "اتاق اضافه" },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 1,
    author: "امیر محمد",
    date: "۱۴۰۳/۰۴/۱۲",
    text: "با سلام، این هتل واقعاً عالی بود. اتاق‌ها تمیز و مجهز بودند و کارکنان بسیار مودب و خوش‌برخورد بودند. حتماً دوباره به اینجا برمی‌گردم.",
    likes: 12,
    liked: false,
    replies: [
      {
        id: 11,
        author: "امیر محمد",
        date: "۱۴۰۳/۰۴/۱۳",
        text: "ممنون از نظر مثبت شما. خوشحالیم که از اقامتتان راضی بودید.",
        likes: 3,
        liked: false,
      },
    ],
  },
  {
    id: 2,
    author: "سارا احمدی",
    date: "۱۴۰۳/۰۳/۲۸",
    text: "هتل خوبی بود ولی صبحانه می‌توانست بهتر باشد. فضای هتل دنج و آرامش‌بخش است.",
    likes: 7,
    liked: false,
  },
  {
    id: 3,
    author: "محمد کریمی",
    date: "۱۴۰۳/۰۳/۱۵",
    text: "موقعیت مکانی عالی، دسترسی به مراکز خرید بسیار راحت. پارکینگ رایگان هم یه امتیاز مثبت بزرگه.",
    likes: 15,
    liked: false,
    replies: [
      {
        id: 31,
        author: "امیر محمد",
        date: "۱۴۰۳/۰۳/۱۶",
        text: "دقیقاً همینطوره، پارکینگ اختصاصی یکی از مزایای اصلی هتله.",
        likes: 5,
        liked: false,
      },
    ],
  },
  {
    id: 4,
    author: "فاطمه رضایی",
    date: "۱۴۰۳/۰۲/۲۰",
    text: "اقامت بسیار خوبی داشتیم. بچه‌ها هم از امکانات استخر لذت بردند. قیمت‌ها هم مناسب بود.",
    likes: 9,
    liked: false,
  },
];

export const listingItems: ListingItem[] = [
  {
    id: 1,
    address: "404",
    beds: 1,
    guests: 3,
    baths: 3,
    area: 3,
    price: 4500000,
    rating: 4.5,
    image: BEDROOM_IMAGES[0],
  },
  {
    id: 2,
    address: "404",
    beds: 1,
    guests: 3,
    baths: 3,
    area: 3,
    price: 4500000,
    rating: 4.5,
    image: BEDROOM_IMAGES[1],
  },
  {
    id: 3,
    address: "404",
    beds: 1,
    guests: 3,
    baths: 3,
    area: 3,
    price: 4500000,
    originalPrice: 5500000,
    discount: 15,
    rating: 4.5,
    image: BEDROOM_IMAGES[2],
  },
  {
    id: 4,
    address: "404",
    beds: 1,
    guests: 3,
    baths: 3,
    area: 3,
    price: 4500000,
    rating: 4.5,
    image: BEDROOM_IMAGES[2],
  },
  {
    id: 5,
    address: "404",
    beds: 1,
    guests: 3,
    baths: 3,
    area: 3,
    price: 4500000,
    originalPrice: 1100000,
    discount: 10,
    rating: 4.5,
    image: BEDROOM_IMAGES[1],
  },
];

export const seedComments: Comment2[] = [
  {
    id: 1,
    name: "امیر محمد",
    handle: "@amiri64",
    date: "شنبه ۱۵ دی ماه ۱۴۰۳، ساعت ۱۴:۳۰",
    text: "سلام، ممنون از ارائه این خانه شگفت‌انگیز. هوش مصنوعی برای این منظور عالی هست.\nبرای اجاره بیشتر از ۶ ماه مبلغی تخفیف دارد یا داریم؟ ممنون از لطفتون 🥰",
    likes: 3,
    liked: false,
  },
  {
    id: 2,
    name: "امیر محمد",
    handle: "@amiri64",
    date: "دوشنبه ۱۷ دی ماه ۱۴۰۳، ساعت ۱۰:۱۵",
    text: "سلام، ممنون از ارائه این خانه شگفت‌انگیز. هوش مصنوعی برای این منظور عالی هست.\nبرای اجاره بیشتر از ۶ ماه مبلغی تخفیف دارد یا داریم؟ ممنون از لطفتون 🥰",
    likes: 5,
    liked: false,
  },
  {
    id: 3,
    name: "امیر محمد",
    handle: "@amiri64",
    date: "سه‌شنبه ۱۸ دی ماه ۱۴۰۳، ساعت ۰۹:۴۵",
    text: "سلام، ممنون از ارائه این خانه شگفت‌انگیز. هوش مصنوعی برای این منظور عالی هست.\nبرای اجاره بیشتر از ۶ ماه مبلغی تخفیف دارد یا داریم؟ ممنون از لطفتون 🥰",
    likes: 2,
    liked: false,
  },
  {
    id: 4,
    name: "امیر محمد",
    handle: "@amiri64",
    date: "چهارشنبه ۱۹ دی ماه ۱۴۰۳، ساعت ۱۶:۰۰",
    text: "سلام، ممنون از ارائه این خانه شگفت‌انگیز. هوش مصنوعی برای این منظور عالی هست.\nبرای اجاره بیشتر از ۶ ماه مبلغی تخفیف دارد یا داریم؟ ممنون از لطفتون 🥰",
    likes: 7,
    liked: false,
  },
  {
    id: 5,
    name: "امیر محمد",
    handle: "@amiri64",
    date: "پنجشنبه ۲۰ دی ماه ۱۴۰۳، ساعت ۱۱:۳۰",
    text: "سلام، ممنون از ارائه این خانه شگفت‌انگیز. هوش مصنوعی برای این منظور عالی هست.\nبرای اجاره بیشتر از ۶ ماه مبلغی تخفیف دارد یا داریم؟ ممنون از لطفتون 🥰",
    likes: 4,
    liked: false,
  },
];
